"""create opportunities table

Revision ID: 26cb16eb16cb
Revises: e71555cf618e
Create Date: 2026-05-18 19:07:29.234784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26cb16eb16cb'
down_revision: Union[str, None] = 'e71555cf618e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_ticker', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('strike_type', sa.String(length=32), nullable=True),
    sa.Column('spot_price', sa.Float(), nullable=True),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('yes_ask', sa.Float(), nullable=True),
    sa.Column('no_ask', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('edge_direction', sa.String(length=8), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('close_time', sa.String(length=64), nullable=True),
    sa.Column('total_contracts', sa.Integer(), nullable=False),
    sa.Column('active_contracts', sa.Integer(), nullable=False),
    sa.Column('market_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fear_greed_value', sa.Integer(), nullable=True),
    sa.Column('fear_greed_label', sa.String(length=32), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_asset'), 'opportunities', ['asset'], unique=False)
    op.create_index(op.f('ix_opportunities_edge'), 'opportunities', ['edge'], unique=False)
    op.create_index(op.f('ix_opportunities_event_ticker'), 'opportunities', ['event_ticker'], unique=False)
    op.create_index(op.f('ix_opportunities_ticker'), 'opportunities', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_ticker'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_event_ticker'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_edge'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_asset'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
