"""add max_exposure_cents to bot_configs

Revision ID: 43db626fce17
Revises: 509dcf0455d5
Create Date: 2026-05-19 11:45:22.031091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43db626fce17'
down_revision: Union[str, None] = '509dcf0455d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('max_exposure_cents', sa.Integer(), nullable=False, server_default='5000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'max_exposure_cents')
    # ### end Alembic commands ###
