"""create analyses table

Revision ID: 50770b1df8d3
Revises: 9152289efb7b
Create Date: 2026-05-18 14:42:56.001118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50770b1df8d3'
down_revision: Union[str, None] = '9152289efb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=256), nullable=True),
    sa.Column('market_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('orderbook_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('trades_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('candles_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('suggested_side', sa.String(length=8), nullable=True),
    sa.Column('key_factors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_ticker'), 'analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_ticker'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
