"""add stop loss and pacing config

Revision ID: 509dcf0455d5
Revises: b2f5cd5d046a
Create Date: 2026-05-19 11:20:37.834990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509dcf0455d5'
down_revision: Union[str, None] = 'b2f5cd5d046a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('stop_loss_cents', sa.Integer(), server_default='10', nullable=False))
    op.add_column('bot_configs', sa.Column('daily_loss_limit_cents', sa.Integer(), server_default='2000', nullable=False))
    op.add_column('bot_configs', sa.Column('max_signals_per_hour', sa.Integer(), server_default='5', nullable=False))
    op.add_column('bot_configs', sa.Column('tier_budget_pct_elite', sa.Integer(), server_default='30', nullable=False))
    op.add_column('bot_configs', sa.Column('tier_budget_pct_high', sa.Integer(), server_default='20', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'tier_budget_pct_high')
    op.drop_column('bot_configs', 'tier_budget_pct_elite')
    op.drop_column('bot_configs', 'max_signals_per_hour')
    op.drop_column('bot_configs', 'daily_loss_limit_cents')
    op.drop_column('bot_configs', 'stop_loss_cents')
    # ### end Alembic commands ###
