"""add realized_drift to signals

Revision ID: 662eae6b3376
Revises: e2679897725b
Create Date: 2026-05-27 12:08:32.225650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662eae6b3376'
down_revision: Union[str, None] = 'e2679897725b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('realized_drift', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'realized_drift')
    # ### end Alembic commands ###
