"""add edge tiers and pnl chart support

Revision ID: b2f5cd5d046a
Revises: b89179a4ec8d
Create Date: 2026-05-19 10:32:13.188872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f5cd5d046a'
down_revision: Union[str, None] = 'b89179a4ec8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('max_position_cents_moderate', sa.Integer(), nullable=False, server_default='750'))
    op.add_column('bot_configs', sa.Column('max_contracts_moderate', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('bot_configs', sa.Column('max_position_cents_high', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('bot_configs', sa.Column('max_contracts_high', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('bot_configs', sa.Column('max_position_cents_elite', sa.Integer(), nullable=False, server_default='2000'))
    op.add_column('bot_configs', sa.Column('max_contracts_elite', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('signals', sa.Column('edge_tier', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_signals_edge_tier'), 'signals', ['edge_tier'], unique=False)
    # Backfill edge_tier for existing signals
    op.execute("UPDATE signals SET edge_tier = 'elite' WHERE model_edge_cents IS NOT NULL AND abs(model_edge_cents) >= 80")
    op.execute("UPDATE signals SET edge_tier = 'high' WHERE model_edge_cents IS NOT NULL AND abs(model_edge_cents) >= 50 AND edge_tier IS NULL")
    op.execute("UPDATE signals SET edge_tier = 'moderate' WHERE model_edge_cents IS NOT NULL AND abs(model_edge_cents) >= 20 AND edge_tier IS NULL")
    op.execute("UPDATE signals SET edge_tier = 'speculative' WHERE model_edge_cents IS NOT NULL AND edge_tier IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_edge_tier'), table_name='signals')
    op.drop_column('signals', 'edge_tier')
    op.drop_column('bot_configs', 'max_contracts_elite')
    op.drop_column('bot_configs', 'max_position_cents_elite')
    op.drop_column('bot_configs', 'max_contracts_high')
    op.drop_column('bot_configs', 'max_position_cents_high')
    op.drop_column('bot_configs', 'max_contracts_moderate')
    op.drop_column('bot_configs', 'max_position_cents_moderate')
    # ### end Alembic commands ###
