"""add take_profit_cents and fill tracking fields

Revision ID: b89179a4ec8d
Revises: e1581e0fdf7c
Create Date: 2026-05-19 09:36:26.563783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89179a4ec8d'
down_revision: Union[str, None] = 'e1581e0fdf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('take_profit_cents', sa.Integer(), server_default='15', nullable=False))
    op.add_column('signals', sa.Column('exit_price_cents', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'filled_at')
    op.drop_column('signals', 'exit_price_cents')
    op.drop_column('bot_configs', 'take_profit_cents')
    # ### end Alembic commands ###
