"""add climate_configs table

Revision ID: c8873adeb3e4
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 15:58:57.738500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8873adeb3e4'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('series_tickers', sa.String(length=256), nullable=False),
    sa.Column('min_volume_24h', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('min_hours_to_expiry', sa.Integer(), nullable=False),
    sa.Column('min_edge', sa.Float(), nullable=False),
    sa.Column('exit_edge', sa.Float(), nullable=False),
    sa.Column('contracts_per_signal', sa.Integer(), nullable=False),
    sa.Column('max_cost_per_signal', sa.Float(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_positions_per_event', sa.Integer(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit_usd', sa.Float(), nullable=False),
    sa.Column('max_signals_per_hour', sa.Integer(), nullable=False),
    sa.Column('min_hold_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_configs_user_id'), 'climate_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_climate_configs_user_id'), table_name='climate_configs')
    op.drop_table('climate_configs')
    # ### end Alembic commands ###
