"""redesign: add bot_configs and signals, drop analyses watchlist orders

Revision ID: e1581e0fdf7c
Revises: e3c0dcb2fd4f
Create Date: 2026-05-19 08:37:41.430347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1581e0fdf7c'
down_revision: Union[str, None] = 'e3c0dcb2fd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_budget_cents', sa.Integer(), nullable=False),
    sa.Column('min_edge_cents', sa.Float(), nullable=False),
    sa.Column('min_liquidity', sa.Float(), nullable=False),
    sa.Column('max_position_cents', sa.Integer(), nullable=False),
    sa.Column('max_contracts_per_signal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_user_id'), 'bot_configs', ['user_id'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('limit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=True),
    sa.Column('model_fair_cents', sa.Float(), nullable=True),
    sa.Column('model_edge_cents', sa.Float(), nullable=True),
    sa.Column('implied_vol', sa.Float(), nullable=True),
    sa.Column('market_yes_price_cents', sa.Float(), nullable=True),
    sa.Column('spot_price', sa.Float(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('kalshi_order_id', sa.String(length=256), nullable=True),
    sa.Column('fill_price_cents', sa.Integer(), nullable=True),
    sa.Column('fill_quantity', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('settled_side', sa.String(length=8), nullable=True),
    sa.Column('pnl_cents', sa.Integer(), nullable=True),
    sa.Column('close_time', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_analyses_event_ticker'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_ticker'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('market_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('orderbook_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trades_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('candles_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('suggested_side', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('key_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_llm_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_ticker', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_event', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('recommended_ticker', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('all_markets_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analyses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analyses_pkey'))
    )
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_analyses_ticker'), 'analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_analyses_event_ticker'), 'analyses', ['event_ticker'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kalshi_order_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('fill_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fill_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('orders_analysis_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('watchlist_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlist_items_pkey')),
    sa.UniqueConstraint('user_id', 'ticker', name=op.f('uq_watchlist_user_ticker'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_bot_configs_user_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    # ### end Alembic commands ###
