"""drop pair_configs table

Revision ID: e2679897725b
Revises: 0fba9db03e65
Create Date: 2026-05-27 11:09:04.132429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2679897725b'
down_revision: Union[str, None] = '0fba9db03e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pair_configs_user_id'), table_name='pair_configs')
    op.drop_table('pair_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('venue', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('contracts_per_signal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stop_loss_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('min_edge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_edge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('pair_configs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pair_configs_pkey')),
    sa.UniqueConstraint('user_id', 'venue', 'pair', name=op.f('uq_pair_config_user_venue_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pair_configs_user_id'), 'pair_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###
