"""add probability model fields to opportunities

Revision ID: e3c0dcb2fd4f
Revises: d00801e17cd3
Create Date: 2026-05-19 07:30:28.588904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c0dcb2fd4f'
down_revision: Union[str, None] = 'd00801e17cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('model_prob', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('model_fair_cents', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('model_edge_cents', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('implied_vol', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'implied_vol')
    op.drop_column('opportunities', 'model_edge_cents')
    op.drop_column('opportunities', 'model_fair_cents')
    op.drop_column('opportunities', 'model_prob')
    # ### end Alembic commands ###
