"""add event fields to analyses

Revision ID: e71555cf618e
Revises: 91cd4fc07021
Create Date: 2026-05-18 15:02:53.722804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e71555cf618e'
down_revision: Union[str, None] = '91cd4fc07021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('event_ticker', sa.String(length=64), nullable=True))
    op.add_column('analyses', sa.Column('is_event', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('analyses', sa.Column('recommended_ticker', sa.String(length=64), nullable=True))
    op.add_column('analyses', sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('all_markets_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_analyses_event_ticker'), 'analyses', ['event_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_event_ticker'), table_name='analyses')
    op.drop_column('analyses', 'all_markets_data')
    op.drop_column('analyses', 'event_data')
    op.drop_column('analyses', 'recommended_ticker')
    op.drop_column('analyses', 'is_event')
    op.drop_column('analyses', 'event_ticker')
    # ### end Alembic commands ###
