"""verbatim initial schema

Revision ID: 78eec3b068c7
Revises: 
Create Date: 2026-08-06 11:49:17.126376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78eec3b068c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_speaker', sa.String(length=200), nullable=True),
    sa.Column('stream_hint', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listening_windows_start', 'listening_windows', ['start_utc'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=120), nullable=False),
    sa.Column('event_ticker', sa.String(length=120), nullable=True),
    sa.Column('series_ticker', sa.String(length=120), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('raw_rules', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.Enum('PENDING', 'PARSED', 'NEEDS_REVIEW', 'RAW_RULES', name='parse_status'), nullable=False),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('deadline_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('armed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('ix_markets_armed_deadline', 'markets', ['armed', 'deadline_utc'], unique=False)
    op.create_table('orderbook_deltas',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticker', sa.String(length=120), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('high_res_retain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orderbook_deltas_ticker_ts', 'orderbook_deltas', ['ticker', 'ts'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticker', sa.String(length=120), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('no', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orderbook_snapshots_ticker_ts', 'orderbook_snapshots', ['ticker', 'ts'], unique=False)
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'ARMED', 'LIVE', 'DEAD', name='stream_status'), nullable=False),
    sa.Column('expected_speaker', sa.String(length=200), nullable=True),
    sa.Column('armed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('variant_kind', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_patterns_market_active', 'match_patterns', ['market_id', 'active'], unique=False)
    op.create_table('service_heartbeats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('service', sa.String(length=60), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_level', sa.Float(), nullable=True),
    sa.Column('chunk_rate', sa.Float(), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_heartbeats_service_ts', 'service_heartbeats', ['service', 'ts'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('capture_wallclock_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_offset_s', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_chunks_stream_ts', 'transcript_chunks', ['stream_id', 'capture_wallclock_utc'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('utterance_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage1_score', sa.Float(), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['match_patterns.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidates_market_ts', 'candidates', ['market_id', 'utterance_ts'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('candidate_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('CONFIRMED', 'REJECTED', name='detection_state'), nullable=False),
    sa.Column('utterance_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage1_transcript', sa.Text(), nullable=False),
    sa.Column('stage2_transcript', sa.Text(), nullable=True),
    sa.Column('matched_span', sa.Text(), nullable=True),
    sa.Column('stage1_score', sa.Float(), nullable=False),
    sa.Column('stage2_score', sa.Float(), nullable=True),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('speaker_is_expected', sa.Boolean(), nullable=True),
    sa.Column('clip_path', sa.Text(), nullable=True),
    sa.Column('chunk_capture_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage1_done_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidate_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage2_done_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_sent_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_reaction_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edge_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['match_patterns.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_market_ts', 'detections', ['market_id', 'utterance_ts'], unique=False)
    op.create_index('ix_detections_state', 'detections', ['state'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.Enum('DETECTION', 'STREAM_DIED', 'NEEDS_REVIEW', 'GPU_RESTART', 'SCHEDULE_SCRAPE_FAILED', name='alert_kind'), nullable=False),
    sa.Column('detection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('click_url', sa.Text(), nullable=True),
    sa.Column('sent_ok', sa.Boolean(), nullable=False),
    sa.Column('send_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_kind_created', 'alerts', ['kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_kind_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_detections_state', table_name='detections')
    op.drop_index('ix_detections_market_ts', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_candidates_market_ts', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_transcript_chunks_stream_ts', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index('ix_service_heartbeats_service_ts', table_name='service_heartbeats')
    op.drop_table('service_heartbeats')
    op.drop_index('ix_match_patterns_market_active', table_name='match_patterns')
    op.drop_table('match_patterns')
    op.drop_table('streams')
    op.drop_index('ix_orderbook_snapshots_ticker_ts', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index('ix_orderbook_deltas_ticker_ts', table_name='orderbook_deltas')
    op.drop_table('orderbook_deltas')
    op.drop_index('ix_markets_armed_deadline', table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_listening_windows_start', table_name='listening_windows')
    op.drop_table('listening_windows')
    # ### end Alembic commands ###
